// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: tasktracker/v1/tasktracker.proto

package tasktrackerv1

import (
	v1 "github.com/lyckety/async_arch/popug_jira/services/task-tracker/pkg/grpc/task/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *TaskCreateRequest) Reset() {
	*x = TaskCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCreateRequest) ProtoMessage() {}

func (x *TaskCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCreateRequest.ProtoReflect.Descriptor instead.
func (*TaskCreateRequest) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{0}
}

func (x *TaskCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TaskCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TaskCreateResponse) Reset() {
	*x = TaskCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCreateResponse) ProtoMessage() {}

func (x *TaskCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCreateResponse.ProtoReflect.Descriptor instead.
func (*TaskCreateResponse) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{1}
}

func (x *TaskCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TaskCompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TaskCompleteRequest) Reset() {
	*x = TaskCompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleteRequest) ProtoMessage() {}

func (x *TaskCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleteRequest.ProtoReflect.Descriptor instead.
func (*TaskCompleteRequest) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{2}
}

func (x *TaskCompleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TaskCompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TaskCompleteResponse) Reset() {
	*x = TaskCompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompleteResponse) ProtoMessage() {}

func (x *TaskCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompleteResponse.ProtoReflect.Descriptor instead.
func (*TaskCompleteResponse) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{3}
}

type TasksShuffleReasignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TasksShuffleReasignRequest) Reset() {
	*x = TasksShuffleReasignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TasksShuffleReasignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksShuffleReasignRequest) ProtoMessage() {}

func (x *TasksShuffleReasignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksShuffleReasignRequest.ProtoReflect.Descriptor instead.
func (*TasksShuffleReasignRequest) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{4}
}

type TasksShuffleReasignResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskToAssignedUser []*TaskIDAndAssignedUserID `protobuf:"bytes,1,rep,name=task_to_assigned_user,json=taskToAssignedUser,proto3" json:"task_to_assigned_user,omitempty"`
}

func (x *TasksShuffleReasignResponse) Reset() {
	*x = TasksShuffleReasignResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TasksShuffleReasignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksShuffleReasignResponse) ProtoMessage() {}

func (x *TasksShuffleReasignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksShuffleReasignResponse.ProtoReflect.Descriptor instead.
func (*TasksShuffleReasignResponse) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{5}
}

func (x *TasksShuffleReasignResponse) GetTaskToAssignedUser() []*TaskIDAndAssignedUserID {
	if x != nil {
		return x.TaskToAssignedUser
	}
	return nil
}

type GetListOpenedTasksForMeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetListOpenedTasksForMeRequest) Reset() {
	*x = GetListOpenedTasksForMeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListOpenedTasksForMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOpenedTasksForMeRequest) ProtoMessage() {}

func (x *GetListOpenedTasksForMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOpenedTasksForMeRequest.ProtoReflect.Descriptor instead.
func (*GetListOpenedTasksForMeRequest) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{6}
}

type GetListOpenedTasksForMeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task []*v1.TaskWithID `protobuf:"bytes,1,rep,name=task,proto3" json:"task,omitempty"`
}

func (x *GetListOpenedTasksForMeResponse) Reset() {
	*x = GetListOpenedTasksForMeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListOpenedTasksForMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOpenedTasksForMeResponse) ProtoMessage() {}

func (x *GetListOpenedTasksForMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOpenedTasksForMeResponse.ProtoReflect.Descriptor instead.
func (*GetListOpenedTasksForMeResponse) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{7}
}

func (x *GetListOpenedTasksForMeResponse) GetTask() []*v1.TaskWithID {
	if x != nil {
		return x.Task
	}
	return nil
}

type TaskIDAndAssignedUserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId         string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AssignedUserId string `protobuf:"bytes,2,opt,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
}

func (x *TaskIDAndAssignedUserID) Reset() {
	*x = TaskIDAndAssignedUserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskIDAndAssignedUserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskIDAndAssignedUserID) ProtoMessage() {}

func (x *TaskIDAndAssignedUserID) ProtoReflect() protoreflect.Message {
	mi := &file_tasktracker_v1_tasktracker_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskIDAndAssignedUserID.ProtoReflect.Descriptor instead.
func (*TaskIDAndAssignedUserID) Descriptor() ([]byte, []int) {
	return file_tasktracker_v1_tasktracker_proto_rawDescGZIP(), []int{8}
}

func (x *TaskIDAndAssignedUserID) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskIDAndAssignedUserID) GetAssignedUserId() string {
	if x != nil {
		return x.AssignedUserId
	}
	return ""
}

var File_tasktracker_v1_tasktracker_proto protoreflect.FileDescriptor

var file_tasktracker_v1_tasktracker_proto_rawDesc = []byte{
	0x0a, 0x20, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x1a, 0x12, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x61, 0x73, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a,
	0x12, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x54, 0x61,
	0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x53, 0x68, 0x75, 0x66, 0x66,
	0x6c, 0x65, 0x52, 0x65, 0x61, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x79, 0x0a, 0x1b, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x53, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65,
	0x52, 0x65, 0x61, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5a, 0x0a, 0x15, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x12, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x6f, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x22, 0x20, 0x0a, 0x1e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b,
	0x73, 0x46, 0x6f, 0x72, 0x4d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a,
	0x1f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x46, 0x6f, 0x72, 0x4d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x57, 0x69, 0x74,
	0x68, 0x49, 0x44, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x5c, 0x0a, 0x17, 0x54, 0x61, 0x73,
	0x6b, 0x49, 0x44, 0x41, 0x6e, 0x64, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x10, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0xb8, 0x03, 0x0a, 0x12, 0x54, 0x61, 0x73, 0x6b,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55,
	0x0a, 0x0a, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x61, 0x73,
	0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x70, 0x0a, 0x13, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x53, 0x68, 0x75, 0x66, 0x66,
	0x6c, 0x65, 0x52, 0x65, 0x61, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x2a, 0x2e, 0x74, 0x61, 0x73, 0x6b,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73,
	0x53, 0x68, 0x75, 0x66, 0x66, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x53, 0x68, 0x75, 0x66,
	0x66, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x7c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x70, 0x65, 0x6e, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x46, 0x6f, 0x72, 0x4d, 0x65, 0x12,
	0x2e, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x46, 0x6f, 0x72, 0x4d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2f, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x54, 0x61,
	0x73, 0x6b, 0x73, 0x46, 0x6f, 0x72, 0x4d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0xe5, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x10, 0x54, 0x61, 0x73, 0x6b, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x64, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x79, 0x63, 0x6b, 0x65, 0x74,
	0x79, 0x2f, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x70, 0x6f, 0x70,
	0x75, 0x67, 0x5f, 0x6a, 0x69, 0x72, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x61, 0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x54, 0x58, 0x58, 0xaa, 0x02, 0x0e, 0x54, 0x61, 0x73, 0x6b,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0e, 0x54, 0x61, 0x73,
	0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1a, 0x54, 0x61,
	0x73, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f, 0x54, 0x61, 0x73, 0x6b, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_tasktracker_v1_tasktracker_proto_rawDescOnce sync.Once
	file_tasktracker_v1_tasktracker_proto_rawDescData = file_tasktracker_v1_tasktracker_proto_rawDesc
)

func file_tasktracker_v1_tasktracker_proto_rawDescGZIP() []byte {
	file_tasktracker_v1_tasktracker_proto_rawDescOnce.Do(func() {
		file_tasktracker_v1_tasktracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_tasktracker_v1_tasktracker_proto_rawDescData)
	})
	return file_tasktracker_v1_tasktracker_proto_rawDescData
}

var file_tasktracker_v1_tasktracker_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tasktracker_v1_tasktracker_proto_goTypes = []interface{}{
	(*TaskCreateRequest)(nil),               // 0: tasktracker.v1.TaskCreateRequest
	(*TaskCreateResponse)(nil),              // 1: tasktracker.v1.TaskCreateResponse
	(*TaskCompleteRequest)(nil),             // 2: tasktracker.v1.TaskCompleteRequest
	(*TaskCompleteResponse)(nil),            // 3: tasktracker.v1.TaskCompleteResponse
	(*TasksShuffleReasignRequest)(nil),      // 4: tasktracker.v1.TasksShuffleReasignRequest
	(*TasksShuffleReasignResponse)(nil),     // 5: tasktracker.v1.TasksShuffleReasignResponse
	(*GetListOpenedTasksForMeRequest)(nil),  // 6: tasktracker.v1.GetListOpenedTasksForMeRequest
	(*GetListOpenedTasksForMeResponse)(nil), // 7: tasktracker.v1.GetListOpenedTasksForMeResponse
	(*TaskIDAndAssignedUserID)(nil),         // 8: tasktracker.v1.TaskIDAndAssignedUserID
	(*v1.TaskWithID)(nil),                   // 9: task.v1.TaskWithID
}
var file_tasktracker_v1_tasktracker_proto_depIdxs = []int32{
	8, // 0: tasktracker.v1.TasksShuffleReasignResponse.task_to_assigned_user:type_name -> tasktracker.v1.TaskIDAndAssignedUserID
	9, // 1: tasktracker.v1.GetListOpenedTasksForMeResponse.task:type_name -> task.v1.TaskWithID
	0, // 2: tasktracker.v1.TaskTrackerService.TaskCreate:input_type -> tasktracker.v1.TaskCreateRequest
	2, // 3: tasktracker.v1.TaskTrackerService.TaskComplete:input_type -> tasktracker.v1.TaskCompleteRequest
	4, // 4: tasktracker.v1.TaskTrackerService.TasksShuffleReasign:input_type -> tasktracker.v1.TasksShuffleReasignRequest
	6, // 5: tasktracker.v1.TaskTrackerService.GetListOpenedTasksForMe:input_type -> tasktracker.v1.GetListOpenedTasksForMeRequest
	1, // 6: tasktracker.v1.TaskTrackerService.TaskCreate:output_type -> tasktracker.v1.TaskCreateResponse
	3, // 7: tasktracker.v1.TaskTrackerService.TaskComplete:output_type -> tasktracker.v1.TaskCompleteResponse
	5, // 8: tasktracker.v1.TaskTrackerService.TasksShuffleReasign:output_type -> tasktracker.v1.TasksShuffleReasignResponse
	7, // 9: tasktracker.v1.TaskTrackerService.GetListOpenedTasksForMe:output_type -> tasktracker.v1.GetListOpenedTasksForMeResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tasktracker_v1_tasktracker_proto_init() }
func file_tasktracker_v1_tasktracker_proto_init() {
	if File_tasktracker_v1_tasktracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tasktracker_v1_tasktracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasktracker_v1_tasktracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasktracker_v1_tasktracker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskCompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasktracker_v1_tasktracker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskCompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasktracker_v1_tasktracker_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TasksShuffleReasignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasktracker_v1_tasktracker_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TasksShuffleReasignResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasktracker_v1_tasktracker_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListOpenedTasksForMeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasktracker_v1_tasktracker_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListOpenedTasksForMeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tasktracker_v1_tasktracker_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskIDAndAssignedUserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tasktracker_v1_tasktracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasktracker_v1_tasktracker_proto_goTypes,
		DependencyIndexes: file_tasktracker_v1_tasktracker_proto_depIdxs,
		MessageInfos:      file_tasktracker_v1_tasktracker_proto_msgTypes,
	}.Build()
	File_tasktracker_v1_tasktracker_proto = out.File
	file_tasktracker_v1_tasktracker_proto_rawDesc = nil
	file_tasktracker_v1_tasktracker_proto_goTypes = nil
	file_tasktracker_v1_tasktracker_proto_depIdxs = nil
}
